//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdmanistNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnketSecimler
    {
        public int id { get; set; }
        public int anketId { get; set; }
        public string description { get; set; }
        public int vote_count { get; set; }
        public int secim_sira { get; set; }
    
        public virtual Anket Anket { get; set; }
    }
}
