//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdmanistNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Nullable<int> opinionId { get; set; }
        public Nullable<int> newsId { get; set; }
        public int id { get; set; }
        public string title { get; set; }
        public string ip { get; set; }
        public string name_surname { get; set; }
        public string content_text { get; set; }
        public string mail { get; set; }
        public bool confirmed { get; set; }
        public int likes { get; set; }
        public int unlike { get; set; }
        public System.DateTime publish_time { get; set; }
    
        public virtual News News { get; set; }
        public virtual Opinion Opinion { get; set; }
    }
}
