//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdmanistNews.cntnt.shop.IdmanistFinal.IdmanistNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public System.Guid id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string img_Route { get; set; }
        public string number { get; set; }
        public string mail { get; set; }
        public int categoryId { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Category Category { get; set; }
    }
}
